language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm

script:
  - phpunit

notifications:
  email:
    recipients:
      - jeroendedauw@gmail.com
    on_success: change
    on_failure: always
  irc:
    channels:
      - "chat.freenode.net#wikidata"
    on_success: change
    on_failure: always
